vich_uploader:
    db_driver: orm

    mappings:
        immobiliers_images:
            uri_prefix: /uploads/images/immobiliers/images
            upload_destination: '%kernel.project_dir%/public/uploads/images/immobiliers/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        immobiliers_medias:
            uri_prefix: /uploads/images/immobiliers/medias
            upload_destination: '%kernel.project_dir%/public/uploads/images/immobiliers/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        annonces_images:
            uri_prefix: /uploads/images/annonces
            upload_destination: '%kernel.project_dir%/public/uploads/images/annonces'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        villes_images:
            uri_prefix: /uploads/images/villes
            upload_destination: '%kernel.project_dir%/public/uploads/images/villes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

        users_avatars:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
